[[redirects]]
  from = "/api/"
  to = "https://api.tide736.net/get_tide.php"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}